{
 "title": "Ecoflow MQTT",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Battery Level",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_bms_status_f32_show_soc"
    }
   ]
  },
  {
   "title": "Inverter IN Watts",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecoflow_inv_input_watts" }
   ]
  },
  {
   "title": "Inverter IN Volts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecoflow_inv_ac_in_vol" }
   ]
  },
  {
   "title": "Inverter IN Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecoflow_inv_ac_in_amp" }
   ]
  },
  {
   "title": "Charging remain time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_ems_status_chg_remain_time"
    }
   ]
  },
  {
   "title": "Full Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_bms_status_full_cap"
    }
   ]
  },
  {
   "title": "BMS Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "abs(ecoflow_bms_bms_status_amp)"
    }
   ]
  },
  {
   "title": "Battery Volts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecoflow_bms_bms_status_vol" }
   ]
  },
  {
   "title": "MIN Cell Volts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_bms_status_min_cell_vol"
    }
   ]
  },
  {
   "title": "MAX Cell Volts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_bms_status_max_cell_vol"
    }
   ]
  },
  {
   "title": "Inverter OUT Watts",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecoflow_inv_output_watts" }
   ]
  },
  {
   "title": "Inverter OUT Volts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecoflow_inv_inv_out_vol" }
   ]
  },
  {
   "title": "Inverter OUT Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecoflow_inv_inv_out_amp" }
   ]
  },
  {
   "title": "Discharging remain time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_ems_status_dsg_remain_time"
    }
   ]
  },
  {
   "title": "Remain Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mamph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_bms_status_remain_cap"
    }
   ]
  },
  {
   "title": "Battery Cycles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecoflow_bms_bms_status_cycles" }
   ]
  },
  {
   "title": "Inverter Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecoflow_inv_out_temp" }
   ]
  },
  {
   "title": "MIN Cell Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_bms_status_min_cell_temp"
    }
   ]
  },
  {
   "title": "MAX Cell Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_bms_status_max_cell_temp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecoflow_bms_bms_status_amp" }
   ]
  },
  {
   "title": "Battery Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ecoflow_bms_bms_status_f32_show_soc",
     "legendFormat": "Battery Level"
    }
   ]
  },
  {
   "title": "IO Watts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "ecoflow_inv_input_watts", "legendFormat": "Input Watts" },
    { "expr": "-ecoflow_inv_output_watts", "legendFormat": "Output Watts" }
   ]
  },
  {
   "title": "Remaining Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "abs(ecoflow_bms_ems_status_chg_remain_time)",
     "legendFormat": "Charging Remain Time"
    },
    {
     "expr": "abs(ecoflow_bms_ems_status_dsg_remain_time)",
     "legendFormat": "Discharging Remain Time"
    }
   ]
  },
  {
   "title": "IO Volts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    { "expr": "ecoflow_inv_ac_in_vol", "legendFormat": "Inverter In" },
    { "expr": "ecoflow_inv_inv_out_vol", "legendFormat": "Inverter Out" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "ecoflow_inv_out_temp", "legendFormat": "Inverter" },
    { "expr": "ecoflow_pd_car_temp", "legendFormat": "PD Car" },
    { "expr": "ecoflow_bms_bms_status_temp", "legendFormat": "BMS" },
    {
     "expr": "ecoflow_bms_bms_status_max_cell_temp",
     "legendFormat": "Max Cell"
    },
    {
     "expr": "ecoflow_bms_bms_status_min_cell_temp",
     "legendFormat": "Min Cell"
    },
    {
     "expr": "ecoflow_bms_bms_status_max_mos_temp",
     "legendFormat": "Max MOS"
    },
    {
     "expr": "ecoflow_bms_bms_status_min_mos_temp",
     "legendFormat": "Min MOS"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    { "expr": "ecoflow_inv_ac_in_amp", "legendFormat": "ecoflow_inv_ac_in_amp" },
    { "expr": "ecoflow_inv_inv_out_amp", "legendFormat": "ecoflow_inv_inv_out_amp" },
    { "expr": "ecoflow_bms_bms_status_amp", "legendFormat": "ecoflow_bms_bms_status_amp" }
   ]
  }
 ]
}